register/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.urls import static
from register import settings
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from thereg import views
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^special/', views.special, name='special'),
    url(r'^thereg/', include('thereg.urls')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    url(r'^logout/$', views.user_logout, name='logout'),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

thereg/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path

from django.conf.urls import url
from thereg import views
# SET THE NAMESPACE!
app_name = 'thereg'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^feedback_form/$', views.feedback_form, name='feedback'),
    url(r'^members/$', views.members, name='members'),
    url(r'^alumni/$', views.alumni, name='alumni'),
    url(r'^varification/$', views.varification, name='varification'),
    path('', views.PostList.as_view(), name='events'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='event_detail'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

thereg/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms
import datetime
# Create your models here.
YEAR = [('1st', 'first'), ('2nd', 'second'), ('3rd', 'third'), ('4th', 'fourth'),
        ('HS or Lower', 'HS or Lower'), ('grad', 'Graduate'), ('PG', 'Post-Graduate')]


class UserProfileInfo(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name='UserProfileInfo')
    Institute = models.CharField(max_length=200, blank=True)
    Department = models.CharField(max_length=200, blank=True)
    Year = models.CharField(max_length=13, choices=YEAR)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    varification_id = models.IntegerField(default=1245)
    varified = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfileInfo.objects.create(user=kwargs['instance'])

    post_save.connect(create_profile, sender=User)


class Feedback(models.Model):
    name = models.CharField(max_length=120)
    email = models.EmailField()
    message = models.TextField()
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name


STATUS = (
    (0, "Draft"),
    (1, "Publish")
)


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    image = models.ImageField(upload_to='media/img',
                              blank=True, default="media/img/transparent.jpg")
    image_1 = models.ImageField(
        upload_to='media/img', blank=True, default='media/img/transparent.jpg')
    image_2 = models.ImageField(
        upload_to='media/img', blank=True, default='media/img/transparent.jpg')
    image_3 = models.ImageField(
        upload_to='media/img', blank=True, default='media/img/transparent.jpg')
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    event_date = models.DateField(default=datetime.date.today)

    class Meta:
        ordering = ['-event_date']

    def __str__(self):
        return self.title


class Member1(models.Model):
    name = models.CharField(max_length=500)
    in_link = models.URLField(blank=True)
    fb_link = models.URLField(blank=True)
    ln_link = models.URLField(blank=True)
    email = models.EmailField(blank=True)
    image = models.ImageField(upload_to="members/first/images")

    def __str__(self):
        return self.name


class Member2(models.Model):
    name = models.CharField(max_length=500)
    in_link = models.URLField(blank=True)
    fb_link = models.URLField(blank=True)
    ln_link = models.URLField(blank=True)
    email = models.EmailField(blank=True)
    image = models.ImageField(upload_to="members/second/images")

    def __str__(self):
        return self.name


class Member3(models.Model):
    name = models.CharField(max_length=500)
    in_link = models.URLField(blank=True)
    fb_link = models.URLField(blank=True)
    ln_link = models.URLField(blank=True)
    email = models.EmailField(blank=True)
    image = models.ImageField(upload_to="members/third/images")

    def __str__(self):
        return self.name


class Member4(models.Model):
    name = models.CharField(max_length=500)
    in_link = models.URLField(blank=True)
    fb_link = models.URLField(blank=True)
    ln_link = models.URLField(blank=True)
    email = models.EmailField(blank=True)
    image = models.ImageField(upload_to="members/fourth/images")
    post = models.CharField(max_length=100)

    def __str__(self):
        return self.name

thereg/forms.py
from django import forms
from thereg.models import UserProfileInfo 
from thereg.models import Feedback
from django.contrib.auth.models import User
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')
class UserProfileInfoForm(forms.ModelForm):
     class Meta():
         model = UserProfileInfo
         fields = ('Institute','Department','Year','profile_pic')






class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        exclude = []

thereg/views.py
from django.shortcuts import render, redirect
from thereg.models import Feedback, Post
# Create your views here.
import random
from django.contrib.auth import get_user_model
from django.shortcuts import render
from thereg.forms import UserForm, UserProfileInfoForm, FeedbackForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.core.mail import send_mail
from django.conf import settings
from thereg.models import Member1, Member2, Member3, Member4


def index(request):
    form = FeedbackForm()
    return render(request, 'thereg/index2.html', {'feedbackform': form})


@login_required
def special(request):
    return HttpResponse("You are logged in !")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    registered = False
    flag = 1
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        User = get_user_model()
        if user_form.is_valid() and profile_form.is_valid():
            for User in User.objects.filter():
                if user_form.cleaned_data['email'] == User.email:
                    flag = 0
                    user_form.cleaned_data['username'] = " "
                    print("This mail address already exists!")

            if flag == 1:
                user = user_form.save()
                print("user saved")
                user.set_password(user.password)
                user.save()

                profile = profile_form.save(commit=False)
                profile.user = user
                varificationId = random.randrange(1000, 9999)
                profile.varification_id = varificationId
                message = "your Varification Id is:" + str(varificationId)
                send_mail(
                    'varify your mail',
                    message,
                    settings.EMAIL_HOST_USER,
                    [user.email],
                    fail_silently=False,
                )

                if 'profile_pic' in request.FILES:
                    print('found it')
                    profile.profile_pic = request.FILES['profile_pic']
                profile.save()
                registered = True
            else:
                print("not-saved")
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request, 'thereg/registration.html',
                  {'user_form': user_form,
                           'profile_form': profile_form,
                           'registered': registered,
                           'flag': flag})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(
                username, password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'thereg/login.html', {})


def feedback_form(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)

        if form.is_valid():
            form.save()
            return render(request, 'thereg/index2.html', {'feedbackform': form})
    else:
        form = FeedbackForm()
    return render(request, 'thereg/index2.html', {'feedbackform': form})


def members(request):
    member4 = Member4.objects.all()
    member3 = Member3.objects.all()
    member2 = Member2.objects.all()
    member1 = Member1.objects.all()

    return render(request, 'thereg/members.html', {"member4": member4, "member3": member3, "member2": member2, "member1": member1})


def alumni(request):

    return render(request, 'thereg/alumni.html', {})


class PostList(generic.ListView):
    model = Post
    template_name = 'thereg/events.html'


class PostDetail(generic.DetailView):
    model = Post
    template_name = 'thereg/event_detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super(PostDetail, self).get_context_data(*args, **kwargs)
        context['post_list'] = Post.objects.all()
        return context


def varification(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        thevarificationid = request.POST.get('Varificationid')
        user = authenticate(username=username, password=password)
        if user:
            print(type(user.UserProfileInfo.varification_id))
            print(type(thevarificationid))
            if user.UserProfileInfo.varification_id == int(thevarificationid):
                user.UserProfileInfo.varified = True
                user.UserProfileInfo.save()
                print("varification-done")
                print(user.UserProfileInfo.varified)
                if user.UserProfileInfo.varified:
                    print("updated")
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("invalid varification details!")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(
                username, password))
            return HttpResponse("Invalid login or varification details details given")
    else:
        return render(request, 'thereg/varifyid.html', {})

templates/thereg/event_detail.html
{% extends 'thereg/eventbase.html' %} {% block content %}


<style type="text/css">
.card-body h1{
  text-transform: uppercase;
}
.container{
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
}
.container-main{
  flex: 64%;
  width: 68%;

}
.container-sidebar{
 flex: 34%;
 width: 28%;
}
  .list-item{
    width: 95%;
    /*height: 130px;*/
    border: 1px solid #dedede;
    margin: 4px;
    color: #000;
    display:flex;
    flex-direction: column;
  }
  .list-header{
    /*height: 60px;*/
    display:flex;
    flex-direction: row;
  }
  .list-img-cont{
    flex: 33.33%;
    width: 33.33%;


  }
  .list-img{
    height: 60px;
    
 

  }
  #listhead.title{
    margin-top: 10px;
    margin-right: 50%;
    font-size: large;
    
  }
  #list.card-text{
    font-size: 18px;
  }
  .title{
    font-size:xx-large;
    }
  .card-text{
    color: #546071;
    font-size: 20px;
  }
  #create.card-text{
    font-size: 17px;
  }
   .list-title{
    padding-left: 10px;
   flex: 66.66%;
   width:66.66%;
   
    
  }
  .list-content{
    padding: 5px;
    padding-top: 6px;
    font-size: 14px;
    color: #000;
  }

  .card.left{
    width: 90%;
  }
  .card-img-bottom{
    width: 100%;
    margin-top: 50px;}
    .img-fluid{
      max-width: 30%;
      margin: 5px;
    }

    .dark_body .card.left{
      background-color: #191919;
    }
  .dark_body .card-text{
      color: #fff;
  }
  .dark_body .title{
      color: #fff;
  }
  .dark_body .list-item{
    background-color: #191919;
  }
  .dark_body .list-title{
    color: #fff;
  }

   @media only screen and (max-width: 1200px){
      .card-text{
        font-size: 30px;
      }
      #create.card-text{
        font-size: 26px;
      }
      #list.card-text{
        font-size: 28px;
      }
      .title{
        font-size:xxx-large;
      }
      #listhead.title{
        margin-top: 12px;
        font-size:x-large;
        margin-right: 50%;
      }

       .img-fluid{
      max-width: 45.5%;
      margin: 5px;
    }
      .container{
        flex-direction: column;
      }
      .container-main{
  
  flex: 100%;
  width: 100%;

}
.container-sidebar{
  padding-top: 8%;
 flex: 100%;
 width: 100%;
}
.card{
  width: 99%;
  margin: 0 auto;
}
.card-body h1{
  font-size: 28px;
}
.list-item{
  width: 98%;
}
    }
</style>
<br><br><br>
<div class="container" style="width: 95%; max-width: unset; margin-bottom: 50px;">

<div class="container-main">
  <div class="row">
    <div class="card left  top">
      <div class="card-body" style="overflow: hidden;">
        <h2 class="title" style="font-weight: 550; overflow: visible; border-bottom: 1px solid #000; padding-bottom: 10px;">{% block title %} {{ object.title }} {% endblock title %}</h2>
        <p class="card-text text-muted" id="create">IEEE SB NIT Dgp  | {{ post.created_on }}</p>
        <p class="card-text" style="margin-bottom: 15px; ; padding-top: 20px; ">{{ object.content | safe }}</p>
        <div class="card-img-bottom">
         {% if not post.image.isempty %}
                     
                    
              <img class="img-fluid" style="opacity: 0.78" src="{{ MEDIA_URL }}{{ post.image.url }}" alt="img" height="">
         {% endif %}
         {% if not post.image_1.isempty %}
                     
                    
              <img class="img-fluid" style="opacity: 0.78" src="{{ MEDIA_URL }}{{ post.image_1.url }}" alt="img" height="">
         {% endif %}
         {% if not post.image_2.isempty %}
                     
                    
              <img class="img-fluid" style="opacity: 0.78" src="{{ MEDIA_URL }}{{ post.image_2.url }}" alt="img" height="">
         {% endif %}
         {% if not post.image_3.isempty %}
                     
                    
              <img class="img-fluid" style="opacity: 0.78" src="{{ MEDIA_URL }}{{ post.image_3.url }}" alt="img" height="">
         {% endif %}
         
       </div>
      </div>
    </div>
    
  </div>
</div>
<div class="container-sidebar">

    {% for event in post_list %}
    
      <div class="list-item">
    <div class="list-header">
        {% if not event.image.isempty %}
        <div class="list-img-cont" style="overflow: hidden;">
             <img class="list-img" style="opacity: 0.8;" src="{{ MEDIA_URL }}{{ event.image.url }}" alt="img" style="">
             </div>
        {% endif %}
        <a class="list-title" href="{% url 'thereg:event_detail' event.slug  %}" style=" color: #000; padding: 0; margin: 0;"><h5 class="title" id="listhead" style="text-align: center;">{{event.title }}</h5></a>
      </div>
        <div class="list-content">
        
        <p class="card-text" id="list" ><small class="text-muted"><i class="fa fa-pencil"></i> {{event.content|slice:":100" }}...</small></p>
        </div>
    
    
  </div>
  <br>
  {% endfor %}
</div>
</div>
{% endblock content %}

templates/thereg/events.html
<!DOCTYPE html>
<html>
{% extends "thereg/eventbase.html" %} 
{% block content %}
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<style type="text/css">
body{
    overflow-x: hidden;
}
.container{

    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    overflow: hidden;
    justify-content: space-around;
}
    .card{
        box-shadow: 0 1px 14px 1px rgba(0, 0, 0, 0.08);
        flex: 32.33%;
        margin-top: 20px;
        max-width: 32.33% !important;
        margin:5px;
        margin-top: 10px;
        margin-bottom: 10px;
        padding: 0;

    }
    .card-title{
        font-size: 28px;
    }
    .card-text{
        font-size: 18px;
        
    }

    .text-muted{
        font-size: 13px;
        padding: 0;
    }
    .back-style{
        height: 190vh;
        width: 99.99vw;
        display: block;
        position: absolute;
        margin-left: 0vw;
        margin-top: 0vh;
        border-radius: 100% 63% 100% 0% / 100% 14% 17% 37%  ;
        background-color: #363dc2; 
    }
    .dark_body .card{
        background-color: #191919;
      }
    .dark_body .card-text{
        color: #fff;
    }
    .dark_body .title{
        color: #fff;
    }
    @media only screen and (max-width: 1200px){
        .card{
        flex: 48%;
        margin-top: 22px;
        max-width: 48% !important;
    }
    .title{
        font-size: xxx-large;
    }
    #dateloc.card-text{
        font-size: 23px;
    }
    #content.card-text{
        font-size: 29px ;
    }
    #read.card-text{
        font-size: 27px;
    }
    }

    @media only screen and (min-width: 800px) and (max-width: 1200px){
        .card{
        flex: 100%;
        margin-top: 40px;
        max-width: 100% !important;
        }
    }
    .card-img-top{
        opacity: 0.75;
    }
</style>
</head>
<body>
    <br>
    <h2 class="title-main" style="margin-bottom: 40px;">All Activities</h2>
<div class="container" style="margin-bottom: 120px; margin-top: 60px;">
    
    {% for post in post_list %}
    <div class="card">
        {% if not post.image.isempty %}
        <div style="overflow: hidden;max-height: 100%;">
             <img class="card-img-top" src="{{ MEDIA_URL }}{{ post.image.url }}" alt="img" style="">
            </div>
        {% endif %}
    
    <div class="card-body">
        <h2 class="title" style="font-weight: 500;overflow: visible; border-bottom: 1px solid #000; padding-bottom: 10px;"><a href="{% url 'thereg:event_detail' post.slug  %}" style="color: inherit;" >{{post.title }}</a></h2>
      <p class="card-text text-muted" id="dateloc"><i class="fa fa-calendar-check-o fa-lg" style="padding-right: 3px;"></i>  {{ post.event_date}}</p>
      <p class="card-text text-muted" id="dateloc"><i class="fa fa-map-marker fa-lg" style="padding-right: 5px;"></i>    NIT Durgapur,India</p>
      
      <p class="card-text" id="content">{{post.content|slice:":200" }}...</p>
      <br>
      <p class="card-text text-muted" id="read"><a href="{% url 'thereg:event_detail' post.slug  %}" class="text-secondary" style="color: #fff !important;background-color: #363dc2; font-weight: 200; padding: 5px; border: 1px solid #363dc2; border-radius: 0.333rem;">Read More<i class="fa fa-arrow">
                </i></a></p>
      
    </div>
  </div>
{% endfor %}
</div>
    
{%endblock%}
</body>

</html>

templates/thereg/index.html
{% extends "thereg/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the Djungle !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/thereg/login.html
{% extends 'thereg/base.html' %}
{% block body_block %}

<style type="text/css">
body{
  background-color: #fff !important;
  

}
.switch_container{
  
}
header{

}
body::-webkit-scrollbar {

  width: 6px;
}
body.dark_body{
  background-color: #656565 !important;
}
  span.input-data{
    display: flex;
    flex-wrap: wrap;
    padding: 8px;
  }
  span.input-data label{
    padding: 3px;
    padding-right: 9px;
    justify-content: center;
    align-items: center;
    padding-top: 5px;
  }
  span.input-data label i{
    font-size: 18px;
    color: #849;

  }
  #top{
    position: unset !important;
    display: none;
  }
  .dark_body span.input-data label i{
    color: #fff;
  }
  span.input-data input{
    background-color: transparent;
    width: 80%;
    border: none !important;
    border-bottom: 1px solid #849 !important;
    overflow-x: unset;
  }
  .dark_body span.input-data input{
    border-color: #fff !important;

  }
  i{
    overflow-x: unset !important;
  }
  span.input-data input:focus{
    border: none;
    border-bottom: 1px solid #849;
  }
  .log-in-block{
    max-width: 500px;
  }
  .reg-container{
    border-radius: 0.33rem;
    padding: 0 !important;
    margin-top: 50px;
    max-width: 500px;
    background-color: #fafafa;
    font-family:'Raleway',Arial, sans-serif;
    -webkit-box-shadow: 4px 11px 47px -8px rgba(0,0,0,0.75);
-moz-box-shadow: 4px 11px 47px -8px rgba(0,0,0,0.75);
box-shadow: 4px 11px 47px -8px rgba(0,0,0,0.75);
margin-bottom: 20px;
  }
  .jumbotron{
    background-color: transparent !important;
  }
  .top-bar-log-in{
    border-radius: 0.33rem;
    min-height: 120px;
    max-width: 100%;
    justify-content: center;
    align-items: center;
    text-align: center;
    color: #fff;
    font-size: 45px;
    padding-top: 32px;
    background-color: #181818;
    padding: 40px;
  }
  .dark_body .top-bar-log-in{
    background-color: #65f;
    
  }
  input[type="submit"]{
    min-width: unset !important;
  }
  .login{
    transition:all 0.3s ease-in-out !important;
  }
  .dark_body .login{
    color: #fff !important;
    border-color: #fff !important;
  }
  .login:hover{
    background-color: #849 !important;
    color: #fff !important;
  }
  .dark_body .reg-container{
    background-color: #454545;
    color: #fff !important;
  }
  .dark_body .reg-container .log-in-block{
    background-color: #454545;
    color: #fff !important;
  }
  .dark_body .reg-container .log-in-block a{
    color: #fff !important;
    border-color: #fff !important;
  }
  .container{
    padding-bottom: 40px;
  }
</style>
  <div class="container reg-container">
    <div class="top-bar-log-in">log-in is only available during any active event registration.</div>
   <!-- <div class="jumbotron log-in-block">
      
<form method="post" action="{% url 'thereg:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <span class="input-data">
          <label for="username"><i class="fa fa-user"></i></label>
          <input type="text" name="username" placeholder="Username"></span>
          <span class="input-data">
          <label for="password"><i class="fa fa-lock"></i></label>
          <input type="password" name="password" placeholder="Password"></span>
<input type="submit" name="" value="Login" style="background-color: transparent; border: 1px solid #849; border-radius: 0.44rem; margin-top: 15px; color: #849; width: 120px;" class="login">
</form>


   <br>
  <p></p>
  <a href="{% url 'social:begin' 'google-oauth2' %}" style="text-decoration: none; color: #849; display: block; padding: 10px; background-color: rgba(250,250,250,0.2); width: 200px; text-align: center; border-radius: 20px; border: 1px solid #849;"><i class="fa fa-google" style="font-size: 18px; padding-right: 2px;"></i>   Login with Google</a><br>
</div>-->
  </div>
{% endblock %}

templates/thereg/registration.html
{% extends "thereg/base.html" %}
{% load staticfiles %}
{% block body_block %}
<style type="text/css">
body{
 background-image: url("http://i.xp.io/15EZVaQh.jpg") !important;
 background-size: 100% !important;
 background-attachment: unset !important;

}
.reg-container{
  display: none;
}
.jumbotron{
  background-color: transparent !important;
}
  .jumbotron p label{
    color: #617 !important;
  }
  .dark_body .jumbotron p label{
    color: #fff !important;
  }
  .reg-container{
    border-radius: 0.33rem;
    padding: 0 !important;
    margin-top: 50px;
    max-width: 500px;
    background-color: #fafafa;
    font-family:'Raleway',Arial, sans-serif;
    -webkit-box-shadow: 4px 11px 47px -8px rgba(0,0,0,0.75);
-moz-box-shadow: 4px 11px 47px -8px rgba(0,0,0,0.75);
box-shadow: 4px 11px 47px -8px rgba(0,0,0,0.75);

margin-bottom: 35px;
  }
   .reg-container input{
    
    margin-left: 5px; 
    font-size: 15px;
    padding: 5px;
    padding-left: 7px;
    min-width: 300px;
   }
   .dark_body .reg-container{
    background-color: #353535;
   }
  .top-bar-reg{
    border-radius: 0.33rem;
    min-height: 120px;
    max-width: 100%;
    justify-content: center;
    align-items: center;
    text-align: center;
    color: #fff;
    font-size: 45px;
    padding-top: 32px;
    background-color: #849;
  }
  .dark_body .top-bar-reg{
    background-color: #65f;
    
  }
  .jumbotron{
   
  padding-top: 5px !important;
  padding-bottom: 10px !important;
  padding-left: 15px !important;
  padding-right: 15px !important;
}
</style>
  <div class="jumbotron" style=" color: #fff;
    font-size: 40px;
    margin: 0;
    text-align: center;
    background-color: rgba(0,0,0,0.7) !important;
    height: 200px;
    margin-top: 40px;
    ">
    No event registration is open now.
  </div>
  <div class="container reg-container">
    <div class="top-bar-reg"><h1 style="line-height: unset !important;">Register Here</h1></div>
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {% if flag == 0 %}
              <h4>This mail adress is already used!</h4>
          {% endif %}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register" class="regis-sub" style="color: #617;">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}